---
title: "The correlation between neighbourhood property crime rates and social factors in Toronto, ON"
#subtitle: "A subtitle"
#thanks: "Paper submitted to complete the requirements of ENVSOCTY 4GA3 Applied Spatial Statistics; with additional edits by Antonio Paez for this version."
author:
- name: Ashmitha Bala
  student_number: 400148743
- name: Cassis Lindsay
  student_number: 400194383
- name: CJ Murphy
  student_number: 400195804
- name: Hayat Shariff
  student_number: 400258691
- name: Zoe Spronk
  student_number: 400231466
subject: "ENVSOCTY 4GA3"
abstract: "This paper reports our analysis of property crime rates in Toronto, ON and their correlation with [INSERT FACTORS HERE] by neighbourhood. Data were retrieved from The City of Toronto Open Data Portal."
keywords: "crime, social factors, spatial analysis"
date: "4/22/2020"
output:
  pdf_document:
    # The project-template-default.tex file was minimally adapted from Steven V. Miller's template for academic manuscripts. See:
    # http://svmiller.com/blog/2016/02/svm-r-markdown-manuscript/
    # https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-latex-ms.tex
    template: project-template-default.tex
bibliography: [bibliography.bib, packages.bib]
always_allow_html: true
---

<!--Chunks of code can have names; the chunk option "include" controls whether the chunk and its output are printed in the final document-->
```{r load-packages, include=FALSE}
library(dplyr) # for accessing Toronto Open Data
library(opendatatoronto) # for accessing Toronto Open Data

library(gridExtra) # for faceting with ggplot
library(plotly) # interactive plotting
library(sf) # working with simple features data
library(spdep) # spatial regression analysis
library(tidyverse) # data manipulation, analysis, and visualization (incl. ggplot2, pipe operators, etc)
library(viridis) # For colour palettes (colour blind friendly)
```

```{r write-package-bib, include=FALSE}
# This function is used to write a bibliography for the `R` packages used in the paper
knitr::write_bib(file = 'packages.bib')
```


```{r get-data, include = FALSE}
# get package
package <- show_package("fc4d95a6-591f-411f-af17-327e6c5d03c7")
package
 
# get all resources for this package
resources <- list_package_resources("fc4d95a6-591f-411f-af17-327e6c5d03c7")
 
# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
 
# load the first datastore resource as a sample
crime_rates <- filter(datastore_resources, row_number()==1) %>% get_resource()
crime_rates
```

```{r aggregating-property-crime-rates, include = FALSE}
#Rates are per 100k
crime_rates <- crime_rates %>%
  mutate(propertyCrime2014 = ((AutoTheft_2014 + BreakAndEnter_2014 + Robbery_2014 + TheftOver_2014)/F2020_Population_Projection)*100000,
         propertyCrime2015 = ((AutoTheft_2015 + BreakAndEnter_2015 + Robbery_2015 + TheftOver_2015)/F2020_Population_Projection)*100000,
         propertyCrime2016 = ((AutoTheft_2016 + BreakAndEnter_2016 + Robbery_2016 + TheftOver_2016)/F2020_Population_Projection)*100000,
         propertyCrime2017 = ((AutoTheft_2017 + BreakAndEnter_2017 + Robbery_2017 + TheftOver_2017)/F2020_Population_Projection)*100000,
         propertyCrime2018 = ((AutoTheft_2018 + BreakAndEnter_2018 + Robbery_2018 + TheftOver_2018)/F2020_Population_Projection)*100000,
         propertyCrime2019 = ((AutoTheft_2019 + BreakAndEnter_2019 + Robbery_2019 + TheftOver_2019)/F2020_Population_Projection)*100000,
         propertyCrime2020 = ((AutoTheft_2020 + BreakAndEnter_2020 + Robbery_2020 + TheftOver_2020)/F2020_Population_Projection)*100000)
```

<!--This create a page break, i.e., starts a new page-->
<!--\newpage-->

<!-- 
To cite references in your bibliography.bib file, use [@item] if you want it to be cited in brackets, or @item if you want it to be cited as Name (year). If you want to cite various items in brackets, separate them with semicolons [@item1; @item2]
-->

<!--Use "#" for section headers-->
<!-- Use * on both sides for bold text, and ** on both sides for italics -->

# Introduction

Insert Introduction Here

# Background

Insert Background Here

# Study area

Insert Study Area Here

# Data

Insert description of data here

# Methods

Insert methods here

# Results

Insert results here

# Analysis

Insert Analysis Here

# Conclusion

Insert Conclusion Here

# References
